export const FETCH_BEER_LIST_REQUEST = "api/FETCH_BEER_LIST_REQUEST"
export const FETCH_BEER_LIST_SUCCESS = "api/FETCH_BEER_LIST_SUCCESS"
export const FETCH_BEER_LIST_ERROR = "api/FETCH_BEER_LIST_ERROR"