export const CHANGE_BEER_FAVORITES_STATE = "favorites/CHANGE_BEER_FAVORITES_STATE"
export const FETCH_FAVORITE_BEERS_REQUEST = "favorites/FETCH_FAVORITE_BEERS_REQUEST"
export const FETCH_FAVORITE_BEERS_SUCCESS = "favorites/FETCH_FAVORITE_BEERS_SUCCESS"
export const FETCH_FAVORITE_BEERS_ERROR = "favorites/FETCH_FAVORITE_BEERS_ERROR"